%% ===== Stage 06C3: Spatial amplitude maps over the analysis window =====
%
% PURPOSE
%   Draw the group-mean spatial distribution of amplitude across the electrode
%   grid for each condition, in the four-panel layout used in the manuscript.
%
% SUPPORTS
%   The topographical maps in the main text. Whether the distribution differs
%   between conditions is tested through the centroid and entropy analyses in
%   Stages 6C1 and 6C4.
%
% INPUT
%   <ROOT>/groupData_stage6A.mat                      (Stage 6A)
%
% OUTPUT
%   <ROOT>/stage6C3_heatmap_mid20to80.mat
%   <ROOT>/Figures_Stage6C3/Stage6C3_spatial_maps.{png,pdf}
%   <ROOT>/stage6C3_centroid.csv
%
% COORDINATES
%   Centred on the geometric middle of the bipolar array:
%       x negative is lateral, positive is medial
%       y negative is proximal, positive is distal
%   Centroids are already stored centred in millimetres and are plotted
%   directly.
%
% NO ECC REVERSAL IS NEEDED
%   Maps are averaged across the whole analysis window, and an average does not
%   depend on sample order.
%
% % ON THE FIGURE
%   The map spans exactly the electrode extent, so the outermost channels sit on
%   its boundary. Their circles are drawn in data units rather than as scatter
%   markers, which lets the axes clip them at the edge instead of letting them
%   overhang it. Panel height is computed from the data proportions rather than
%   set by axis equal, so each map fills its rectangle and the colour bar, the
%   brackets and the scale bars all keep their alignment.
%
% ON THE COLOUR SCALE
%   Amplitude limits are taken from the data across all four conditions, so the
%   maps are directly comparable and nothing saturates. A perceptually uniform
%   colormap is used rather than jet, which introduces apparent boundaries where
%   the data are smooth.
%
% ON THE INTERPOLATION
%   The surface between electrodes is interpolated for display only. Every
%   statistic in this pipeline is computed on the channel values themselves.
%
% ON MANUAL ADJUSTMENT
%   Every element of the figure is generated by this script: the maps, the
%   electrode positions, the centroids, the colour scale and the scale bars. The
%   placement of the labels, brackets and compass was then adjusted by hand
%   against the output until the spacing read cleanly, and the values arrived at
%   are the ones set in section (1). Nothing in the data is affected by that
%   tuning.
%
%   The commented lines at the end of the file cover the case where a figure is
%   nudged further in the Property Inspector and saved from there.
%
% RUNNING THIS STAGE
%   Standalone, run the script and choose the data root when prompted. From the
%   pipeline driver, set CFG.ROOT beforehand and the prompt is skipped.
%
% DEPENDENCIES
%   Statistics and Machine Learning Toolbox   ttest
%   turbo colormap requires R2020b or later; parula is used otherwise.

close all;

%% ---------------------------
%  (1) Options
%% ---------------------------
% The driver may set any of these in CFG before calling. Fields are only filled
% in here when absent, so a one-button run and a standalone run behave the same.

if ~exist('CFG','var') || ~isstruct(CFG), CFG = struct(); end

CFG = set_default(CFG, 'binName',      'all');      % 'all' | 'early' | 'late'
CFG = set_default(CFG, 'midWin',       [20 80]);    % analysis window, % of CV
CFG = set_default(CFG, 'saveFigures',  true);

% Interpolation onto the display grid
CFG = set_default(CFG, 'interpMethod', 'natural');
CFG = set_default(CFG, 'extrapMethod', 'nearest');
CFG = set_default(CFG, 'nInterpX',     121);
CFG = set_default(CFG, 'nInterpY',     241);

% Colour limits
CFG = set_default(CFG, 'climMode',     'auto');     % 'auto' or 'manual'
CFG = set_default(CFG, 'climManual',   [20 80]);    % used only when manual
CFG = set_default(CFG, 'climPad',      0.02);       % headroom on the auto range

% Marker geometry, in millimetres so the circles scale with the map
CFG = set_default(CFG, 'electrodeRadius_mm', 1.6);
CFG = set_default(CFG, 'electrodeLineWidth', 1.4);
CFG = set_default(CFG, 'centroidLineWidth',  2.2);

% Figure layout, all in normalised figure units unless noted
CFG = set_default(CFG, 'figSize',   [1100 560]);   % pixels
CFG = set_default(CFG, 'leftM',     0.045);
CFG = set_default(CFG, 'gapPair',   0.008);        % between CON and ECC
CFG = set_default(CFG, 'gapMid',    2*CFG.gapPair);% between intensity pairs
CFG = set_default(CFG, 'cbGap',     0.012);
CFG = set_default(CFG, 'cbWidth',   0.020);
CFG = set_default(CFG, 'rightM',    0.085);        % room for the colour bar label
CFG = set_default(CFG, 'panelBottom', 0.10);
CFG = set_default(CFG, 'panelHeight', 0.66);

binName = CFG.binName;
midWin  = CFG.midWin;

%% ---------------------------
%  (2) Data root and group data
%% ---------------------------
% The driver sets CFG.ROOT. Standalone, the folder is always chosen through the
% dialog, so a variable left over from an earlier run cannot silently redirect
% the analysis to the wrong data.
if ~isfield(CFG,'ROOT') || ~(ischar(CFG.ROOT) || isstring(CFG.ROOT)) || strlength(string(CFG.ROOT)) == 0
    picked = uigetdir(pwd, 'Select the ROOT data folder (contains 01, 02, 03, ...)');
    if isequal(picked,0)
        error('Stage 6C3: no data root selected.');
    end
    CFG.ROOT = picked;
end
ROOT = char(CFG.ROOT);
validate_root(ROOT);

groupFile = fullfile(ROOT,'groupData_stage6A.mat');
assert(isfile(groupFile), ...
    'Stage 6C3: %s not found. Run Stage 6A first.', groupFile);

L = load(groupFile);
assert(isfield(L,'groupData'), 'File does not contain "groupData".');
groupData = L.groupData;

figDir = fullfile(ROOT,'Figures_Stage6C3');
if CFG.saveFigures && ~exist(figDir,'dir'), mkdir(figDir); end

fprintf('\n===== Stage 6C3: spatial amplitude maps =====\n');
fprintf('Root: %s\n', ROOT);
fprintf('Participants %d | bin %s | window %d-%d %%CV\n', ...
    groupData.nSub, binName, midWin(1), midWin(2));

%% ---------------------------
%  (3) Condition indices and required fields
%% ---------------------------
condNames = string(groupData.conditions);
idx = struct();
for c = ["CON_75","ECC_75","CON_90","ECC_90"]
    k = find(condNames == c, 1);
    assert(~isempty(k), 'Condition %s not found.', c);
    idx.(erase(c,"_")) = k;
end

assert(isfield(groupData.bipolar, binName) && ...
       isfield(groupData.bipolar.(binName),'emgRMS_bipNorm_101'), ...
    'groupData.bipolar.%s.emgRMS_bipNorm_101 missing.', binName);
assert(isfield(groupData.timeseries.(binName),'centroidXc_101'), 'Centroid X missing.');
assert(isfield(groupData.coords,'x_center_mm'), 'coords.x_center_mm missing.');
assert(isfield(groupData.mapInfo,'bipolar_rowcol'), 'mapInfo.bipolar_rowcol missing.');

% Channel count and electrode spacing taken from the data rather than assumed
rc = groupData.mapInfo.bipolar_rowcol;
nB = size(rc,1);

if isfield(groupData,'centroid_params') && isfield(groupData.centroid_params,'IED_mm')
    IED_mm = groupData.centroid_params.IED_mm;
else
    IED_mm = 10;
end

%% ---------------------------
%  (4) Window mask
%% ---------------------------
xAxis_full = groupData.xAxis(:).';
midMask = xAxis_full >= midWin(1) & xAxis_full <= midWin(2);
assert(any(midMask), 'No samples inside the requested window.');
fprintf('Window covers %d of %d samples\n', nnz(midMask), numel(xAxis_full));

%% ---------------------------
%  (5) Per-participant maps, averaged across the window
%% ---------------------------
bipTS = groupData.bipolar.(binName).emgRMS_bipNorm_101;   % [nSub x 4 x nB x nT]
assert(ndims(bipTS) == 4 && size(bipTS,3) == nB, ...
    'Unexpected bipolar array shape.');

mapSub = mean(bipTS(:,:,:,midMask), 4, 'omitnan');        % [nSub x 4 x nB]

M = struct();
for c = ["CON75","ECC75","CON90","ECC90"]
    M.(c) = squeeze(mean(mapSub(:, idx.(c), :), 1, 'omitnan'));
    M.(c) = M.(c)(:);
end

%% ---------------------------
%  (6) Centroids, averaged across the window
%% ---------------------------
Cx = groupData.timeseries.(binName).centroidXc_101;
Cy = groupData.timeseries.(binName).centroidYc_101;

CxSub = squeeze(mean(Cx(:,:,midMask), 3, 'omitnan'));     % [nSub x 4]
CySub = squeeze(mean(Cy(:,:,midMask), 3, 'omitnan'));

xc = struct(); yc = struct();
for c = ["CON75","ECC75","CON90","ECC90"]
    xc.(c) = mean(CxSub(:, idx.(c)), 'omitnan');
    yc.(c) = mean(CySub(:, idx.(c)), 'omitnan');
end

%% ---------------------------
%  (7) Centroid statistics
%% ---------------------------
% Reported for cross-checking against Stage 6B, which is where the manuscript
% values come from. Note the sign convention differs: this stage reports ECC
% minus CON, Stage 6B reports CON minus ECC.

fprintf('\n===== CENTROID, %d-%d%% CV window =====\n', midWin(1), midWin(2));
cRows = {};

for I = ["75","90"]
    cc = "CON"+I;  ee = "ECC"+I;
    for AX = ["X","Y"]
        if AX == "X", Sc = CxSub; else, Sc = CySub; end
        a = Sc(:, idx.(cc));      % CON
        b = Sc(:, idx.(ee));      % ECC

        % ECC minus CON throughout, so the mean, t and CI all share one sign.
        d = b - a;
        [~, pv, ci, st] = ttest(b, a);
        dz = mean(d,'omitnan') / std(d,0,'omitnan');

        fprintf(['%s %s%%: CON %+.3f +/- %.3f | ECC %+.3f +/- %.3f | ' ...
                 't(%d) = %.2f, p = %.5f, dz = %+.2f\n'], ...
            AX, I, mean(a,'omitnan'), std(a,0,'omitnan'), ...
            mean(b,'omitnan'), std(b,0,'omitnan'), st.df, st.tstat, pv, dz);

        cRows(end+1,:) = {AX, I, mean(a,'omitnan'), std(a,0,'omitnan'), ...
            mean(b,'omitnan'), std(b,0,'omitnan'), mean(d,'omitnan'), ...
            st.tstat, st.df, pv, dz, ci(1), ci(2)}; %#ok<SAGROW>
    end
end

writetable(cell2table(cRows, 'VariableNames', ...
    {'axis','intensity','CON_mean','CON_sd','ECC_mean','ECC_sd','diff_ECCminusCON', ...
     't','df','p','dz','ci_lo','ci_hi'}), ...
    fullfile(ROOT,'stage6C3_centroid.csv'));

% Per-participant centroid values, for the supplement
centroidTable = table(string(groupData.participants), ...
    CxSub(:,idx.CON75), CySub(:,idx.CON75), CxSub(:,idx.ECC75), CySub(:,idx.ECC75), ...
    CxSub(:,idx.CON90), CySub(:,idx.CON90), CxSub(:,idx.ECC90), CySub(:,idx.ECC90), ...
    'VariableNames', {'Participant', ...
    'Cx_CON75','Cy_CON75','Cx_ECC75','Cy_ECC75', ...
    'Cx_CON90','Cy_CON90','Cx_ECC90','Cy_ECC90'});

%% ---------------------------
%  (8) Electrode coordinates, centred
%% ---------------------------
% The display grid spans exactly the electrode extent, so the outermost circles
% sit on the boundary and are clipped there.

x_ch = (rc(:,2) - 1) * IED_mm - groupData.coords.x_center_mm;
y_ch = ((rc(:,1) - 1) * IED_mm + IED_mm/2) - groupData.coords.y_center_mm;

xq = linspace(min(x_ch), max(x_ch), CFG.nInterpX);
yq = linspace(min(y_ch), max(y_ch), CFG.nInterpY);
[Xq, Yq] = meshgrid(xq, yq);

%% ---------------------------
%  (9) Interpolated surfaces
%% ---------------------------
Z = struct();
for c = ["CON75","ECC75","CON90","ECC90"]
    Z.(c) = interp_map(x_ch, y_ch, M.(c), Xq, Yq, CFG.interpMethod, CFG.extrapMethod);
end

% Shared amplitude limits so the four maps are directly comparable
if strcmpi(CFG.climMode,'auto')
    allZ = [Z.CON75(:); Z.ECC75(:); Z.CON90(:); Z.ECC90(:)];
    lo = min(allZ,[],'omitnan');
    hi = max(allZ,[],'omitnan');
    pad = CFG.climPad * (hi - lo);
    climMVA = [floor(lo - pad) ceil(hi + pad)];
else
    climMVA = CFG.climManual;
end

fprintf('\nAmplitude scale: %.0f to %.0f %%MVA (shared across conditions)\n', ...
    climMVA(1), climMVA(2));

%% ---------------------------
%  (10) Figure, all four conditions
%% ---------------------------
cmapAmp = perceptual_map(256);
figs = struct();

figW = CFG.figSize(1); figH = CFG.figSize(2);
figs.maps = figure('Color','w','Name','Spatial maps | all conditions', ...
                   'Position',[100 100 figW figH]);

% --- layout geometry ---
availW = 1 - CFG.leftM - 2*CFG.gapPair - CFG.gapMid ...
           - CFG.cbGap - CFG.cbWidth - CFG.rightM;
pw = availW/4;

dataW = xq(end) - xq(1);
dataH = yq(end) - yq(1);

% Panel height that reproduces the true map proportions at this figure size, so
% the axes fill their rectangles and nothing shifts when the window changes.
ph = pw * (dataH/dataW) * (figW/figH);
pb = CFG.panelBottom;

px = [CFG.leftM, ...
      CFG.leftM + pw + CFG.gapPair, ...
      CFG.leftM + 2*pw + CFG.gapPair + CFG.gapMid, ...
      CFG.leftM + 3*pw + 2*CFG.gapPair + CFG.gapMid];

mapBottom = pb;
mapHeight = ph;
mapTop    = pb + ph;

% 2 mm and 1 mm in figure units, used to offset the labels and the scale bars
pad2mm = ph * (2/dataH);
off1mm = pw * (1/dataW);

% --- maps ---
panelOrder = ["CON75","ECC75","CON90","ECC90"];
panelLabel = ["CON","ECC","CON","ECC"];

axm = gobjects(1,4);
for k = 1:4
    axm(k) = axes('Position',[px(k) pb pw ph]);
    c = panelOrder(k);
    plot_map_bare(axm(k), xq, yq, Z.(c), x_ch, y_ch, xc.(c), yc.(c), ...
        climMVA, CFG, cmapAmp);
end

% --- condition labels, 2 mm above each map ---
for k = 1:4
    annotation('textbox', [px(k) mapTop+pad2mm pw 0.055], ...
        'String', panelLabel(k), 'EdgeColor','none', ...
        'HorizontalAlignment','center', 'VerticalAlignment','bottom', ...
        'FontWeight','bold', 'FontSize', 12);
end

% --- intensity brackets, spanning panel centre to panel centre ---
bracketY = mapTop + pad2mm + 0.065;
draw_bracket(px(1)+pw/2, px(2)+pw/2, bracketY, '75% MVC');
draw_bracket(px(3)+pw/2, px(4)+pw/2, bracketY, '90% MVC');

% --- anatomical compass, centred above the whole layout ---
compassR = 0.038;
compassX = (px(1) + px(4) + pw) / 2;
draw_compass(compassX, mapTop + compassR + pad2mm + 0.045, compassR, figW/figH);

% --- scale bars, one inter-electrode distance, mirrored across the middle gap ---
sbLenY = ph * (IED_mm/dataH);
sbLenX = pw * (IED_mm/dataW);
sbBot  = mapBottom;

xL = px(2) + pw + off1mm;          % right of the 75% pair
annotation('line', [xL xL], [sbBot sbBot+sbLenY], 'LineWidth', 3, 'Color','k');
annotation('line', [xL-sbLenX xL], [sbBot sbBot], 'LineWidth', 3, 'Color','k');

xR = px(3) - off1mm;               % left of the 90% pair
annotation('line', [xR xR], [sbBot sbBot+sbLenY], 'LineWidth', 3, 'Color','k');
annotation('line', [xR xR+sbLenX], [sbBot sbBot], 'LineWidth', 3, 'Color','k');

% Label rotated between the two vertical arms. The box is wide along the text
% direction and wrapping is off, so "10 mm" stays on one line.
annotation('textbox', [(xL+xR)/2 - 0.06, sbBot, 0.12, sbLenY], ...
    'String','10 mm', 'EdgeColor','none', 'FontWeight','bold', ...
    'FontSize', 10, 'Rotation', 90, 'FitBoxToText','off', ...
    'HorizontalAlignment','center', 'VerticalAlignment','middle');

% --- colour bar, matched to the map height ---
cb = colorbar(axm(4), 'Position', ...
    [px(4) + pw + CFG.cbGap, mapBottom, CFG.cbWidth, mapHeight]);
cb.Label.String = 'RMS EMG [% MVA]';
cb.Label.FontWeight = 'bold';
cb.FontSize = 11; cb.FontWeight = 'bold';
cb.TickDirection = 'out'; cb.LineWidth = 1.0;

if CFG.saveFigures
    exportgraphics(figs.maps, ...
        fullfile(figDir,'Stage6C3_spatial_maps.png'), 'Resolution', 600);
    exportgraphics(figs.maps, ...
        fullfile(figDir,'Stage6C3_spatial_maps.pdf'), 'ContentType','vector');
    fprintf('Figure saved to %s\n', figDir);
end
%% ---------------------------
%  (11) Save
%% ---------------------------
stage6C3 = struct();
stage6C3.meta = struct( ...
    'createdOn', char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), ...
    'script', mfilename, 'sourceFile', groupFile, 'binName', binName, ...
    'midWin_percentCV', midWin, ...
    'nBipolar', nB, 'IED_mm', IED_mm, 'climMVA', climMVA, ...
    'sign_note', "centroid differences in the CSV are ECC minus CON", ...
    'note', ["maps are averaged across the analysis window, so no ECC " ...
             "reversal is required"]);

stage6C3.maps     = M;
stage6C3.mapsSub  = mapSub;
stage6C3.centroid = struct('x', CxSub, 'y', CySub, 'table', centroidTable);
stage6C3.coords   = struct('x_ch', x_ch, 'y_ch', y_ch);

save(fullfile(ROOT,'stage6C3_heatmap_mid20to80.mat'), 'stage6C3', '-v7.3');

fprintf('\nSaved results  : %s\n', fullfile(ROOT,'stage6C3_heatmap_mid20to80.mat'));
fprintf('Saved centroid : %s\n', fullfile(ROOT,'stage6C3_centroid.csv'));

%% =========================================================
%  Local functions
%% =========================================================
function S = set_default(S, fieldName, value)
% Fills a config field only when the caller has not already supplied it.
    if ~isfield(S, fieldName) || isempty(S.(fieldName))
        S.(fieldName) = value;
    end
end

function validate_root(ROOT)
% Confirms the chosen folder looks like the expected layout, so that a wrong
% selection fails immediately with a useful message rather than partway through
% a batch.
    assert(isfolder(ROOT), 'Data root not found at %s', ROOT);

    D = dir(ROOT);
    D = D([D.isdir] & ~startsWith({D.name},'.'));

    hasParticipant = false;
    for i = 1:numel(D)
        pPath = fullfile(ROOT, D(i).name);
        C = dir(pPath);
        C = C([C.isdir]);
        if any(~cellfun(@isempty, regexp({C.name},'^(CON|ECC)_\d+$','once')))
            hasParticipant = true;
            break;
        end
    end

       % A folder holding only the processed group file is a valid root for the
    % Stage 6 analyses, which read nothing else.
    hasGroupFile = isfile(fullfile(ROOT,'groupData_stage6A.mat'));

    assert(hasParticipant || hasGroupFile, ...
        ['The selected folder does not look like the expected data root.\n' ...
         'Expected either the raw layout\n' ...
         '  <ROOT>/<participant>/<CON_75|CON_90|ECC_75|ECC_90>/<Set_N>/\n' ...
         'or a folder containing groupData_stage6A.mat\n' ...
         'Selected: %s'], ROOT);
end

function Z = interp_map(x, y, v, Xq, Yq, interpMethod, extrapMethod)
% Interpolates the channel values onto the display grid. This is for display
% only; every statistic is computed on the channel values themselves.
    x = x(:); y = y(:); v = v(:);
    ok = isfinite(x) & isfinite(y) & isfinite(v);
    F = scatteredInterpolant(x(ok), y(ok), v(ok), interpMethod, extrapMethod);
    Z = F(Xq, Yq);
end

function C = perceptual_map(n)
% Perceptually uniform sequential map. Uses turbo where available, which is
% ordered and colourful without the false boundaries jet introduces, and falls
% back to parula on older releases.
    try
        C = turbo(n);
    catch
        C = parula(n);
    end
end

function plot_map_bare(ax, xq, yq, Z, x_ch, y_ch, xc, yc, climVals, CFG, cmap)
% One interpolated map with no axis decoration and no bounding box.
%
% The electrode circles are drawn in data units rather than as scatter markers.
% Scatter markers are drawn whole regardless of the axes limits, so the ones on
% the boundary would overhang the map; a plotted circle is clipped at the edge,
% which is the intended look.

    imagesc(ax, xq, yq, Z);
    set(ax,'YDir','normal');
       hold(ax,'on');
    % Both aspect modes stay automatic, so the axes fills the rectangle it was
    % given. The true map proportions come from the panel height computed in
    % section (10) instead.
    set(ax,'DataAspectRatioMode','auto','PlotBoxAspectRatioMode','auto');

    colormap(ax, cmap);
    clim(ax, climVals);

    th  = linspace(0, 2*pi, 61);
    rad = CFG.electrodeRadius_mm;

    for e = 1:numel(x_ch)
        plot(ax, x_ch(e) + rad*cos(th), y_ch(e) + rad*sin(th), ...
            'k-', 'LineWidth', CFG.electrodeLineWidth, 'Clipping','on');
    end

    if isfinite(xc) && isfinite(yc)
        plot(ax, xc + rad*cos(th), yc + rad*sin(th), ...
            'w-', 'LineWidth', CFG.centroidLineWidth, 'Clipping','on');
    end

    set(ax,'XTick',[],'YTick',[],'Box','off','XColor','none','YColor','none');
    xlim(ax,[xq(1) xq(end)]);
    ylim(ax,[yq(1) yq(end)]);
end

function draw_bracket(x0, x1, y, labelStr)
% Horizontal bracket with downward ticks at each end, labelled above. The ends
% sit at the centres of the two panels the bracket spans.
    tick = 0.018;
    annotation('line', [x0 x1], [y y],        'LineWidth', 1.2, 'Color','k');
    annotation('line', [x0 x0], [y-tick y],   'LineWidth', 1.2, 'Color','k');
    annotation('line', [x1 x1], [y-tick y],   'LineWidth', 1.2, 'Color','k');
    annotation('textbox', [x0 y+0.005 x1-x0 0.06], 'String', labelStr, ...
        'EdgeColor','none', 'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', 'FontWeight','bold', 'FontSize', 12);
end

function draw_compass(cx, cy, r, figAspect)
% Anatomical directions: distal up, proximal down, lateral left, medial right.
% The horizontal arm is scaled by the figure aspect so the cross reads square.
    rx = r / figAspect;
    a = {'HeadStyle','vback2','HeadLength',6,'HeadWidth',6, ...
         'LineWidth',1.2,'Color','k'};
    annotation('arrow', [cx cx],    [cy cy+r], a{:});
    annotation('arrow', [cx cx],    [cy cy-r], a{:});
    annotation('arrow', [cx cx-rx], [cy cy],   a{:});
    annotation('arrow', [cx cx+rx], [cy cy],   a{:});

    t = {'EdgeColor','none','FontWeight','bold','FontSize',11, ...
         'HorizontalAlignment','center','VerticalAlignment','middle'};
    annotation('textbox', [cx-0.02      cy+r+0.005  0.04 0.04], 'String','D', t{:});
    annotation('textbox', [cx-0.02      cy-r-0.045  0.04 0.04], 'String','P', t{:});
    annotation('textbox', [cx-rx-0.045  cy-0.02     0.04 0.04], 'String','L', t{:});
    annotation('textbox', [cx+rx+0.005  cy-0.02     0.04 0.04], 'String','M', t{:});
end


% Manual export, when a figure has been adjusted by hand in the Property
% Inspector. Close plot edit mode first, or the edit handles are exported too.
%
% plotedit(gcf, 'off')
% [f,p] = uiputfile('Figure.png','Save figure as');
%exportgraphics(gcf, fullfile(p,f), 'Resolution', 1000);